# Travis CI build configuration config file.
language: php

python:
  - 5.5

addons:
  hosts:
    - localhost
  apt:
    packages:
    # - drush # See: https://github.com/travis-ci/apt-package-whitelist/issues/1611
    - realpath
    - tree

notifications:
  email:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always

# Environment
sudo: false
env:
  global:
    - MODULES="booking_timeslots"
    - COMPOSER_BIN_DIR=~/bin
    - PATH=${PATH//:\.\/node_modules\/\.bin/} # Fixes Travis bug: https://github.com/travis-ci/travis-ci/issues/4862

  matrix:
    - CORE=7 DRUSH_EN="booking_timeslots_example"

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - env
  - set -e # Fail build on first error.
  - echo "sendmail_path='true'" | tee -a $(php --ini | grep "Loaded Configuration" | awk '{print $4}')

install:
  - composer require drush/drush:dev-master
  - drush -y dl coder --destination=~/.drush && drush cc drush

before_script:
  - drush qd --yes --server=:80 --watchdog --core=drupal-$CORE testsite $MODULES && cd drupal-*

script:
  - drush core-requirements --severity=2
  - drush review summary major comment,i18n,security,sql,style $MODULES

after_success:

after_failure:
 - sudo wget -qO- http://$HOSTNAME/ | cat
 - drush --version
 - drush core-requirements --severity=2
 - drush status --full
 - drush ws --full
 - tree -d -L 6 # Print directory structure in the form of a tree.

after_script:
 - echo $TRAVIS_TEST_RESULT
