<?php

/**
 * @file
 *   Theme include file
 *
 * @version
 *
 * @developers
 *   Rafal Wieczorek <kenorb@gmail.com>
 */

/**
 * Theme preprocess callback
 *
 * Format an calendar day node for display.
 */
function template_preprocess_booking_timeslots_day_node(&$vars) {
  // TODO: placeholder for some preprocess code
  // See: template_preprocess_calendar_node($vars);
}


/**
 * Theme preprocess callback
 *
 * Format an calendar month node for display.
 */
function template_preprocess_booking_timeslots_month_node(&$vars) {
  // TODO: placeholder for some preprocess code
  // See: template_preprocess_calendar_node($vars);
}

/**
 * Theme preprocess callback
 *
 * Format an calendar week node for display.
 */
function template_preprocess_booking_timeslots_week_node(&$vars) {
  // TODO: placeholder for some preprocess code
  // See: template_preprocess_calendar_node($vars);
}

